### ISSUE TITLE
Benchmarking in CI is broken

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#419]
All PRs are returning `N/A` on benchmarking workflows.

Here is an example `bench-cpu.yaml` file:

```yaml
cases:
  5eq_rk3_weno3_hllc:
    description:
      args:
      - -c
      - phoenix
      - -n
      - '4'
      path: /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/benchmarks/5eq_rk3_weno3_hllc/case.py
      slug: 5eq_rk3_weno3_hllc
    output_summary:
      invocation:
      - run
      - /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/benchmarks/5eq_rk3_weno3_hllc/case.py
      - '1'
      - --case-optimization
      - --targets
      - pre_process
      - simulation
      - post_process
      - --output-summary
      - /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/build/benchmarks/a596/5eq_rk3_weno3_hllc.yaml
      - -c
      - phoenix
      - -n
      - '4'
      lock:
        debug: false
        gpu: false
        mpi: true
      pre_process: 1
      syscheck: 1
  hypo_hll:
    description:
      args:
      - -c
      - phoenix
      - -n
      - '4'
      path: /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/benchmarks/hypo_hll/case.py
      slug: hypo_hll
    output_summary:
      invocation:
      - run
      - /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/benchmarks/hypo_hll/case.py
      - '1'
      - --case-optimization
      - --targets
      - pre_process
      - simulation
      - post_process
      - --output-summary
      - /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/build/benchmarks/a596/hypo_hll.yaml
      - -c
      - phoenix
      - -n
      - '4'
      lock:
        debug: false
        gpu: false
        mpi: true
      pre_process: 1
      syscheck: 0
  ibm:
    description:
      args:
      - -c
      - phoenix
      - -n
      - '4'
      path: /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/benchmarks/ibm/case.py
      slug: ibm
    output_summary:
      invocation:
      - run
      - /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/benchmarks/ibm/case.py
      - '1'
      - --case-optimization
      - --targets
      - pre_process
      - simulation
      - post_process
      - --output-summary
      - /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/build/benchmarks/a596/ibm.yaml
      - -c
      - phoenix
      - -n
      - '4'
      lock:
        debug: false
        gpu: false
        mpi: true
      pre_process: 1
      syscheck: 1
  viscous_weno5_sgb_mono:
    description:
      args:
      - -c
      - phoenix
      - -n
      - '4'
      path: /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/benchmarks/viscous_weno5_sgb_mono/case.py
      slug: viscous_weno5_sgb_mono
    output_summary:
      invocation:
      - run
      - /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/benchmarks/viscous_weno5_sgb_mono/case.py
      - '1'
      - --case-optimization
      - --targets
      - pre_process
      - simulation
      - post_process
      - --output-summary
      - /storage/coda1/p-sbryngelson3/0/sbryngelson3/runners/actions-runner-3/_work/MFC/MFC/master/build/benchmarks/a596/viscous_weno5_sgb_mono.yaml
      - -c
      - phoenix
      - -n
      - '4'
      lock:
        debug: false
        gpu: false
        mpi: true
      pre_process: 2
      syscheck: 0
metadata:
  invocation:
  - bench
  - --mem
  - '1'
  - -j
  - '24'
  - -o
  - bench-cpu.yaml
  - --
  - -c
  - phoenix
  - -n
  - '4'
  lock:
    debug: false
    gpu: false
    mpi: true
```
